"""Neuroweave Report Generator 📊
────────────────────────────────────────────
Generates a prediction summary and simulated market report.
"""

import datetime

def generate_prediction_report(tickers: list, predictions: list, user: str = "anonymous") -> str:
    date = datetime.date.today().isoformat()
    header = f"# 📈 Neuroweave Market Report\n\nDate: **{date}**\nPrepared for: **{user}**\n\n---\n"
    
    report = header
    for symbol, summary in zip(tickers, predictions):
        report += f"### ${symbol}\n- Summary: {summary}\n- Confidence: ~{round(70 + hash(symbol) % 20)}%\n\n"

    report += "\n\n> This is a simulated report generated by Neuroweave. Not financial advice.\n"
    return report
